/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PharmacyRouteImport } from './routes/pharmacy'
import { Route as LaboratoryRouteImport } from './routes/laboratory'
import { Route as DoctorsRouteImport } from './routes/doctors'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChairmanZulmanSaeedRouteImport } from './routes/chairman-zulman-saeed'
import { Route as ChairmanMuzammilAbdulKhaderRouteImport } from './routes/chairman-muzammil-abdul-khader'
import { Route as CeoTKMuhammadSafeemRouteImport } from './routes/ceo-t-k-muhammad-safeem'
import { Route as BookAppointmentRouteImport } from './routes/book-appointment'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacyRoute = PharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LaboratoryRoute = LaboratoryRouteImport.update({
  id: '/laboratory',
  path: '/laboratory',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsRoute = DoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChairmanZulmanSaeedRoute = ChairmanZulmanSaeedRouteImport.update({
  id: '/chairman-zulman-saeed',
  path: '/chairman-zulman-saeed',
  getParentRoute: () => rootRouteImport,
} as any)
const ChairmanMuzammilAbdulKhaderRoute =
  ChairmanMuzammilAbdulKhaderRouteImport.update({
    id: '/chairman-muzammil-abdul-khader',
    path: '/chairman-muzammil-abdul-khader',
    getParentRoute: () => rootRouteImport,
  } as any)
const CeoTKMuhammadSafeemRoute = CeoTKMuhammadSafeemRouteImport.update({
  id: '/ceo-t-k-muhammad-safeem',
  path: '/ceo-t-k-muhammad-safeem',
  getParentRoute: () => rootRouteImport,
} as any)
const BookAppointmentRoute = BookAppointmentRouteImport.update({
  id: '/book-appointment',
  path: '/book-appointment',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/book-appointment': typeof BookAppointmentRoute
  '/ceo-t-k-muhammad-safeem': typeof CeoTKMuhammadSafeemRoute
  '/chairman-muzammil-abdul-khader': typeof ChairmanMuzammilAbdulKhaderRoute
  '/chairman-zulman-saeed': typeof ChairmanZulmanSaeedRoute
  '/contact': typeof ContactRoute
  '/departments': typeof DepartmentsRoute
  '/disclaimer': typeof DisclaimerRoute
  '/doctors': typeof DoctorsRoute
  '/laboratory': typeof LaboratoryRoute
  '/pharmacy': typeof PharmacyRoute
  '/portal': typeof PortalRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/products': typeof ProductsRoute
  '/sitemap': typeof SitemapRoute
  '/team': typeof TeamRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/book-appointment': typeof BookAppointmentRoute
  '/ceo-t-k-muhammad-safeem': typeof CeoTKMuhammadSafeemRoute
  '/chairman-muzammil-abdul-khader': typeof ChairmanMuzammilAbdulKhaderRoute
  '/chairman-zulman-saeed': typeof ChairmanZulmanSaeedRoute
  '/contact': typeof ContactRoute
  '/departments': typeof DepartmentsRoute
  '/disclaimer': typeof DisclaimerRoute
  '/doctors': typeof DoctorsRoute
  '/laboratory': typeof LaboratoryRoute
  '/pharmacy': typeof PharmacyRoute
  '/portal': typeof PortalRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/products': typeof ProductsRoute
  '/sitemap': typeof SitemapRoute
  '/team': typeof TeamRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/book-appointment': typeof BookAppointmentRoute
  '/ceo-t-k-muhammad-safeem': typeof CeoTKMuhammadSafeemRoute
  '/chairman-muzammil-abdul-khader': typeof ChairmanMuzammilAbdulKhaderRoute
  '/chairman-zulman-saeed': typeof ChairmanZulmanSaeedRoute
  '/contact': typeof ContactRoute
  '/departments': typeof DepartmentsRoute
  '/disclaimer': typeof DisclaimerRoute
  '/doctors': typeof DoctorsRoute
  '/laboratory': typeof LaboratoryRoute
  '/pharmacy': typeof PharmacyRoute
  '/portal': typeof PortalRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/products': typeof ProductsRoute
  '/sitemap': typeof SitemapRoute
  '/team': typeof TeamRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/book-appointment'
    | '/ceo-t-k-muhammad-safeem'
    | '/chairman-muzammil-abdul-khader'
    | '/chairman-zulman-saeed'
    | '/contact'
    | '/departments'
    | '/disclaimer'
    | '/doctors'
    | '/laboratory'
    | '/pharmacy'
    | '/portal'
    | '/privacy-policy'
    | '/products'
    | '/sitemap'
    | '/team'
    | '/terms-and-conditions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/book-appointment'
    | '/ceo-t-k-muhammad-safeem'
    | '/chairman-muzammil-abdul-khader'
    | '/chairman-zulman-saeed'
    | '/contact'
    | '/departments'
    | '/disclaimer'
    | '/doctors'
    | '/laboratory'
    | '/pharmacy'
    | '/portal'
    | '/privacy-policy'
    | '/products'
    | '/sitemap'
    | '/team'
    | '/terms-and-conditions'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/book-appointment'
    | '/ceo-t-k-muhammad-safeem'
    | '/chairman-muzammil-abdul-khader'
    | '/chairman-zulman-saeed'
    | '/contact'
    | '/departments'
    | '/disclaimer'
    | '/doctors'
    | '/laboratory'
    | '/pharmacy'
    | '/portal'
    | '/privacy-policy'
    | '/products'
    | '/sitemap'
    | '/team'
    | '/terms-and-conditions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BookAppointmentRoute: typeof BookAppointmentRoute
  CeoTKMuhammadSafeemRoute: typeof CeoTKMuhammadSafeemRoute
  ChairmanMuzammilAbdulKhaderRoute: typeof ChairmanMuzammilAbdulKhaderRoute
  ChairmanZulmanSaeedRoute: typeof ChairmanZulmanSaeedRoute
  ContactRoute: typeof ContactRoute
  DepartmentsRoute: typeof DepartmentsRoute
  DisclaimerRoute: typeof DisclaimerRoute
  DoctorsRoute: typeof DoctorsRoute
  LaboratoryRoute: typeof LaboratoryRoute
  PharmacyRoute: typeof PharmacyRoute
  PortalRoute: typeof PortalRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProductsRoute: typeof ProductsRoute
  SitemapRoute: typeof SitemapRoute
  TeamRoute: typeof TeamRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy': {
      id: '/pharmacy'
      path: '/pharmacy'
      fullPath: '/pharmacy'
      preLoaderRoute: typeof PharmacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laboratory': {
      id: '/laboratory'
      path: '/laboratory'
      fullPath: '/laboratory'
      preLoaderRoute: typeof LaboratoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors': {
      id: '/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof DoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chairman-zulman-saeed': {
      id: '/chairman-zulman-saeed'
      path: '/chairman-zulman-saeed'
      fullPath: '/chairman-zulman-saeed'
      preLoaderRoute: typeof ChairmanZulmanSaeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chairman-muzammil-abdul-khader': {
      id: '/chairman-muzammil-abdul-khader'
      path: '/chairman-muzammil-abdul-khader'
      fullPath: '/chairman-muzammil-abdul-khader'
      preLoaderRoute: typeof ChairmanMuzammilAbdulKhaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ceo-t-k-muhammad-safeem': {
      id: '/ceo-t-k-muhammad-safeem'
      path: '/ceo-t-k-muhammad-safeem'
      fullPath: '/ceo-t-k-muhammad-safeem'
      preLoaderRoute: typeof CeoTKMuhammadSafeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-appointment': {
      id: '/book-appointment'
      path: '/book-appointment'
      fullPath: '/book-appointment'
      preLoaderRoute: typeof BookAppointmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BookAppointmentRoute: BookAppointmentRoute,
  CeoTKMuhammadSafeemRoute: CeoTKMuhammadSafeemRoute,
  ChairmanMuzammilAbdulKhaderRoute: ChairmanMuzammilAbdulKhaderRoute,
  ChairmanZulmanSaeedRoute: ChairmanZulmanSaeedRoute,
  ContactRoute: ContactRoute,
  DepartmentsRoute: DepartmentsRoute,
  DisclaimerRoute: DisclaimerRoute,
  DoctorsRoute: DoctorsRoute,
  LaboratoryRoute: LaboratoryRoute,
  PharmacyRoute: PharmacyRoute,
  PortalRoute: PortalRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProductsRoute: ProductsRoute,
  SitemapRoute: SitemapRoute,
  TeamRoute: TeamRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
